### PR TITLE
:sparkles: Added Rich Console

### LINKED ISSUE #5: Add fancy Command-Line Menu to accept RFC number
use a library like `rich` to create a fancy menu to take in the RFC Number,

### PR DESCRIPTION
**Pull request by anirudhlakhotia**
RFC number is no more permanent while running the file

### CODE REVIEW

**Comment by anirudhRowjee** [comment]
Hi! How does one access the menu?
running 
```
$ python3 main.py
```
gives me an error for not selecting the RFC number, and running
```
$ python3 main.py 959
```
gives me the output directly.

**Comment by anirudhlakhotia** [comment]
> Hi! How does one access the menu? running
> 
> ```
> $ python3 main.py
> ```
> 
> gives me an error for not selecting the RFC number, and running
> 
> ```
> $ python3 main.py 959
> ```
> 
> gives me the output directly.

if you don't give it a number, there's no error, the console pops up and asks the user to enter a number, 15 by default

**Comment by anirudhRowjee** [comment]
LGTM

**Comment by anirudhRowjee** [comment]
!bounty 30

**Pull request merged**
